sudo: required
services:
  - docker

before_install:
  - docker build -t hannanshaikyara/docker-react -f Dockerfile.dev .  

script:
  - docker run hannanshaikyara/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-788100186019'
  bucket_path: 'docker-react'
  on: 
    branch: 'master'
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"