sudo: required
services:
  - docker

before_install:
  - docker build -t hannanshaikyara/docker-react -f Dockerfile.dev .  

script:
  - docker run hannanshaikyara/docker-react yarn test -- --coverage